import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="bg-[#fbcc07] rounded-b-2xl h-12 w-full ">
          <div className="  container m-auto">
            <div className="text-white">

              ADMISION
            </div>
          </div>
        </div>
        <div>
          <Navbar />
        </div>
        <main className="   ">

          {children}
          <div>
            <img src="/icons/whatsapp.svg" alt="" className="fixed bottom-4 sm:top-1/2 animate-bounce " />
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
